# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Interfaz.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.



import json
from datetime import date
from PyQt5 import QtCore, QtGui, QtWidgets
from Cedis_MAT import *



TextBoxAdd = {}
TextBoxInd = {}
TextBoxAll = {}
AllOptions = []

FechasAvailable = []
def AddOptionsBox():
        Bills = getAllBills()
        for item in Bills:
            AllOptions.append(Bills[item])
        


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(720, 480)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 720, 480))
        self.tabWidget.setObjectName("tabWidget")
        self.AgregarElemento = QtWidgets.QWidget()
        self.AgregarElemento.setObjectName("AgregarElemento")
        self.Elementos = QtWidgets.QComboBox(self.AgregarElemento)
        self.Elementos.setGeometry(QtCore.QRect(30, 90, 200, 22))
        self.Elementos.setObjectName("Elementos")
        self.Elementos.addItem("")
        self.Elementos.setEditable(True)
        self.Elementos.addItems(AllOptions)
        self.Cantidad = QtWidgets.QSpinBox(self.AgregarElemento)
        self.Cantidad.setGeometry(QtCore.QRect(250, 90, 42, 22))
        self.Cantidad.setObjectName("Cantidad")
        self.AgregarElementoButton = QtWidgets.QPushButton(self.AgregarElemento)
        self.AgregarElementoButton.setGeometry(QtCore.QRect(350, 90, 75, 23))
        self.AgregarElementoButton.setObjectName("AgregarElementoButton")
        self.AgregarElementoButton.clicked.connect(self.OrdenGen)
        self.FechaElemento = QtWidgets.QDateEdit(self.AgregarElemento)
        self.FechaElemento.setGeometry(QtCore.QRect(70, 40, 110, 22))
        self.FechaElemento.setObjectName("FechaElemento")
        self.ElementosCompletos = QtWidgets.QTextBrowser(self.AgregarElemento)
        self.ElementosCompletos.setGeometry(QtCore.QRect(130, 140, 256, 192))
        self.ElementosCompletos.setObjectName("ElementosCompletos")

        ##Second Page

        self.tabWidget.addTab(self.AgregarElemento, "")
        self.AgregarIndividual = QtWidgets.QWidget()
        self.AgregarIndividual.setObjectName("AgregarIndividual")
        self.Fecha_individual = QtWidgets.QDateEdit(self.AgregarIndividual)
        self.Fecha_individual.setGeometry(QtCore.QRect(70, 30, 110, 22))
        self.Fecha_individual.setObjectName("Fecha_individual")
        self.AgregarComponenteButton = QtWidgets.QPushButton(self.AgregarIndividual)
        self.AgregarComponenteButton.setGeometry(QtCore.QRect(350, 80, 75, 23))
        self.AgregarComponenteButton.setObjectName("AgregarComponenteButton")
        self.AgregarComponenteButton.clicked.connect(self.IndividualGen)
        self.CantidadIndividual = QtWidgets.QSpinBox(self.AgregarIndividual)
        self.CantidadIndividual.setGeometry(QtCore.QRect(250, 80, 42, 22))
        self.CantidadIndividual.setObjectName("CantidadIndividual")
        self.ElementosIndividuales = QtWidgets.QTextBrowser(self.AgregarIndividual)
        self.ElementosIndividuales.setGeometry(QtCore.QRect(230, 120, 256, 192))
        self.ElementosIndividuales.setObjectName("ElementosIndividuales")
        self.OptionElementos = QtWidgets.QComboBox(self.AgregarIndividual)
        self.OptionElementos.setGeometry(QtCore.QRect(240, 30, 181, 22))
        self.OptionElementos.setObjectName("OptionElementos")
        self.OptionElementos.setEditable(True)
        self.OptionElementos.addItems(AllOptions)
        self.OptionComponente = QtWidgets.QComboBox(self.AgregarIndividual)
        self.OptionComponente.setGeometry(QtCore.QRect(60, 80, 141, 22))
        self.OptionComponente.setObjectName("OptionComponente")
        self.BuscarComponentes = QtWidgets.QPushButton(self.AgregarIndividual)
        self.BuscarComponentes.setGeometry(QtCore.QRect(450, 30, 200, 23))
        self.BuscarComponentes.setObjectName("BuscarComponentes")
        self.BuscarComponentes.clicked.connect(self.BuscarIndv)


        ##THIRD PAGE
        self.tabWidget.addTab(self.AgregarIndividual, "")
        self.Visualizar = QtWidgets.QWidget()
        self.Visualizar.setObjectName("Visualizar")
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.Visualizar)
        self.textBrowser_3.setGeometry(QtCore.QRect(30, 10, 341, 271))
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.GenerarOrden = QtWidgets.QPushButton(self.Visualizar)
        self.GenerarOrden.setGeometry(QtCore.QRect(414, 122, 150, 21))
        self.GenerarOrden.setObjectName("GenerarOrden")
        self.GenerarOrden.clicked.connect(self.CrearOrden)
        self.Borrar = QtWidgets.QPushButton(self.Visualizar)
        self.Borrar.setGeometry(QtCore.QRect(414, 202, 150, 21))
        self.Borrar.setObjectName("Borrar")
        self.Borrar.clicked.connect(self.BorrarAll)
        self.HighRunnerButton = QtWidgets.QPushButton(self.Visualizar)
        self.HighRunnerButton.setGeometry(QtCore.QRect(414, 282, 150, 21))
        self.HighRunnerButton.setObjectName("HighRunner")
        self.HighRunnerButton.clicked.connect(self.HighRunner)

        self.tabWidget.addTab(self.Visualizar, "")
        self.EliminarIndividual = QtWidgets.QWidget()
        self.EliminarIndividual.setObjectName("EliminarIndividual")
        self.EliminarIndividualBoton = QtWidgets.QPushButton(self.EliminarIndividual)
        self.EliminarIndividualBoton.setGeometry(QtCore.QRect(290, 170, 75, 23))
        self.EliminarIndividualBoton.setObjectName("EliminarIndividualBoton")
        self.EliminarIndividualBoton.clicked.connect(self.BorrarIndv)
        self.FechasEliminar = QtWidgets.QComboBox(self.EliminarIndividual)
        self.FechasEliminar.setGeometry(QtCore.QRect(130, 130, 161, 22))
        self.FechasEliminar.setObjectName("FechasEliminar")
        self.FechasEliminar.setEditable(True)
        # self.OptionElementos.addItems("Fechas")
        
        self.tabWidget.addTab(self.EliminarIndividual, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 588, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Elementos.setItemText(0, _translate("MainWindow", "Elementos"))
        self.BuscarComponentes.setText( _translate("MainWindow", "Buscar Componentes"))
        self.AgregarElementoButton.setText(_translate("MainWindow", "Agregar"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.AgregarElemento), _translate("MainWindow", "Agregar Elemento"))
        self.AgregarComponenteButton.setText(_translate("MainWindow", "Agregar"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.AgregarIndividual), _translate("MainWindow", "Agregar Componente"))
        self.textBrowser_3.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.GenerarOrden.setText(_translate("MainWindow", "Generar Reporte"))
        self.Borrar.setText(_translate("MainWindow", "Borrar"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Visualizar), _translate("MainWindow", "Visualizar"))
        self.EliminarIndividualBoton.setText(_translate("MainWindow", "Eliminar"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.EliminarIndividual), _translate("MainWindow", "Eliminar Individual"))
        self.HighRunnerButton.setText(_translate("MainWindow", "High Runners"))


    def BuscarIndv(self):
        self.OptionComponente.clear()
        Item = self.OptionElementos.currentText()
        Components = GetIndividualComponents(Item)
        for item in Components:
            
            item = str(item)
            self.OptionComponente.addItem(item)


    def OrdenGen(self):
        Elemento = self.Elementos.currentText()
        Fecha = self.FechaElemento.text()
        Cantidad = int(self.Cantidad.text())
        OrderDate(Fecha)
        ActualOrder ={}
        ActualOrder[Elemento] = Cantidad

        ADDORDER(ActualOrder,Fecha)
        self.ElementosCompletos.clear()
        self.ElementosIndividuales.clear()
        self.textBrowser_3.clear()
        # print(finishedOrders)
       
        self.ElementosCompletos.append(json.dumps(finishedOrders))
        self.ElementosIndividuales.append(json.dumps(finishedOrders))
        self.textBrowser_3.append(json.dumps(finishedOrders))


        
        if Fecha not in FechasAvailable:
            self.FechasEliminar.addItem(Fecha)
            FechasAvailable.append(Fecha)
            
        

    
    def IndividualGen(self):
        Elemento = self.OptionComponente.currentText()
        try:
            Elemento = int(Elemento)
        except:
            Elemento = str(Elemento)
        Fecha = self.Fecha_individual.text()
        Cantidad = int(self.CantidadIndividual.text())
        AgregarIndividual(Elemento,Fecha,Cantidad)
        self.ElementosCompletos.clear()
        self.ElementosIndividuales.clear()
        self.textBrowser_3.clear()
        # print(finishedOrders)
       
        self.ElementosCompletos.append(json.dumps(finishedOrders))
        self.ElementosIndividuales.append(json.dumps(finishedOrders))
        self.textBrowser_3.append(json.dumps(finishedOrders))


    def CrearOrden(self):

        ordenesFinales = CheckAvailable(finishedOrders,inventario,dateOrder)
        # print(ordenesFinales)
        # print(dateOrder)
        firstWarning = list(ordenesFinales)[0]
        GenerarReporte(ordenesFinales,firstWarning,finishedOrders,dateOrder,inventario)
        sys.exit()
        
    def BorrarAll(self):
        DeleteALL()
        self.ElementosCompletos.clear()
        self.ElementosIndividuales.clear()
        self.textBrowser_3.clear()
        
       
        self.ElementosCompletos.append(json.dumps(finishedOrders))
        self.ElementosIndividuales.append(json.dumps(finishedOrders))
        self.textBrowser_3.append(json.dumps(finishedOrders))



    def BorrarIndv(self):

        FechaBorrar = self.FechasEliminar.currentText()
        DeleteOne(FechaBorrar)
        count =0 
        for i in FechasAvailable:
            if i == FechaBorrar:

                self.FechasEliminar.removeItem(count)
                FechasAvailable.pop(count)
            count+=1

        self.ElementosCompletos.clear()
        self.ElementosIndividuales.clear()
        self.textBrowser_3.clear()
        self.ElementosCompletos.append(json.dumps(finishedOrders))
        self.ElementosIndividuales.append(json.dumps(finishedOrders))
        self.textBrowser_3.append(json.dumps(finishedOrders))

    def HighRunner(self):
        amount = 150
     
        for x in Runners:
           
            print(x)
            ADDORDER({x:amount},self.FechaElemento.text())
            
        OrderDate(self.FechaElemento.text())
        
        ordenFinal =  CheckAvailable(finishedOrders,inventario,dateOrder)
        firstWarning = list(ordenFinal)[0]
        GenerarReporte(ordenFinal,firstWarning,finishedOrders,dateOrder,inventario,1)
        sys.exit()
        
        

        
if __name__ == "__main__":
    AddOptionsBox()
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    
    MainWindow.show()
    sys.exit(app.exec_())
