# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Inv.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from Inventario import *

Sites = []

def loadSite():
    GetLocation()
    

class Ui_MainWindow(object):
    Alocation = []
    
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.SearchSite = QtWidgets.QPushButton(self.centralwidget)
        self.SearchSite.setGeometry(QtCore.QRect(370, 70, 75, 23))
        self.SearchSite.setObjectName("SearchSite")
        self.SearchSite.clicked.connect(self.LocationSearch)
        self.Site = QtWidgets.QComboBox(self.centralwidget)
        self.Site.setGeometry(QtCore.QRect(150, 70, 181, 22))
        self.Site.setObjectName("Site")
        self.Site.setEditable(True)
        self.Site.addItems(Sites)
        self.Location = QtWidgets.QComboBox(self.centralwidget)
        self.Location.setGeometry(QtCore.QRect(150, 140, 181, 22))
        self.Location.setObjectName("Location") 
        self.SearchLocation = QtWidgets.QPushButton(self.centralwidget)
        self.SearchLocation.setGeometry(QtCore.QRect(370, 140, 75, 23))
        self.SearchLocation.setObjectName("SearchLocation")
        self.SearchLocation.clicked.connect(self.AddLocation)
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(140, 240, 201, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_3.clicked.connect(self.LoadInventory)
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(350, 180, 171, 141))
        self.textBrowser.setObjectName("textBrowser")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.SearchSite.setText(_translate("MainWindow", "Buscar"))
        self.SearchLocation.setText(_translate("MainWindow", "Buscar"))
        self.pushButton_3.setText(_translate("MainWindow", "Cargar Inventario"))


    def LocationSearch(self):
        self.Location.clear()
        Site = self.Site.currentText()
        SiteLocations(Site)
        Location = availableLocations
        self.Location.addItem("ALL")
        for item in Location:
            
            item = str(item)
            
            self.Location.addItem(item)

    def AddLocation(self):
        
        if self.Location.currentText()=="ALL":
            self.Alocation = availableLocations
        else:
            if self.Alocation == availableLocations:
                self.Alocation=[]
            if self.Location.currentText() not in self.Alocation:
             self.Alocation.append(self.Location.currentText())

        self.textBrowser.clear()

        for x in self.Alocation:
            
            self.textBrowser.append(x)

    def LoadInventory(self):
        AddInventario(self.Alocation,SelectedSites)
        self.textBrowser.clear()
        self.Alocation= []

if __name__ == "__main__":
    import sys
    loadSite()
    Sites = availableSites
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    
    MainWindow.show()
    sys.exit(app.exec_())
